default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: job-t-bot-development

test:
  <<: *default
  database: job-t-bot-test

production:
  <<: *default
  database: job-t-bot-production
