development: &dev
  secret_key_base: <%= ENV['TELEGRAM_SECRET_KEY_BASE'] %>
  telegram:
    bot:
      token: <%= ENV['TELEGRAM_BOT_TOKEN'] %>
      username: JobTBot
      # async: true

test:
  <<: *dev

production:
  <<: *dev
